### ISSUE TITLE
Add Drag and Drop

### ISSUE THREAD

**Issue by cngeru** [maxwellhaydn/react-simple-chessboard#2]
How do we add drag and drop ? I'm a willing contributor.

**Comment by cngeru** [comment]
Hoping to get rid off jQuery in the process too

**Comment by maxwellhaydn** [comment]
@cngeru Thanks for your interest! It's quite easy to add drag-and-drop because react-simple-chessboard is just a wrapper around chessboard.js. The only change would be adding a property to the Chessboard component and passing the value to the chessboard.js constructor.

The jQuery dependency comes from chessboard.js. Eliminating that would basically involve re-implementing chessboard.js.

You might want to look at [https://www.chessboardjsx.com/](chessboardjsx), which already has a lot more functionality than react-simple-chessboard, including drag-and-drop. It also doesn't require jQuery. The only problem is it appears to be unmaintained.

**Comment by cngeru** [comment]
After digging into the code I understood why you needed jquery.
I was using chessboardjsx and decided to look for another option for a project I'm working on
Chessboard.js has loads of functionality that I would wish to see ported to react.
hoping to migrate to this lib soon. Thank you

**Comment by maxwellhaydn** [comment]
I've added drag-and-drop support in v1.1.0. See the updated README for instructions on how to use it.

The author of chessboardjsx recently added a note saying that it's unmaintained. Instead of porting too many features from chessboardjsx to react-simple-chessboard, I would rather try to take over maintenance of chessboardjsx and fix any issues it has, but that would be a large effort.

**Comment by cngeru** [comment]
Can react-chess.js be used with chessboardjsx ?
Hope the author gives you control 🙏.

**Comment by maxwellhaydn** [comment]
react-chess.js can be used with chessboardjsx to some extent already, but would need more work to support more use cases. For example, react-chess.js only understands moves in algebraic notation (e.g. "Nf3"), but chessboardjsx's `onDrop` callback is called with an object with properties `sourceSquare`, `targetSquare`, and `piece`. To do move validation when you drag-and-drop a piece, react-chess.js will need to  be updated to also support this format for moves.

**Comment by cngeru** [comment]
Check out this project they use chessboard.js [https://github.com/Phongtlam/reactchess]( https://github.com/Phongtlam/reactchess)

**Comment by cngeru** [comment]
Hello,
1. Been having problems updating the board state and validating the moves using useChess..

Here is my code for the first problem 
```
  const handleLegalMove = (move) => {
    console.log(move)
  };

  const handleGameOver = () => {
    setStatus({ severity: 'success', message: 'Game over' });
  };

  const handleStalemate = () => {
    setStatus({ severity: 'info', message: 'Stalemate' });
  };

  const handleCheck =()=>{
    setStatus({ severity: 'info', message: 'Check' });
  }

  const handleCheckMate =()=>{
    setStatus({ severity: 'info', message: 'Checkmate' });
  }

  const {move,history,fen,turn} = useChess({
    onLegalMove: handleLegalMove,
    onIllegalMove: move => console.log(move),
    onGameOver: handleGameOver,
    onCheck: handleCheck,
    onCheckmate:handleCheckMate,
    onDraw: () => setStatus({ severity: 'info', message: 'Stalemate' }),
    onStalemate: handleStalemate,
    onThreefoldRepetition: () => setStatus({ severity: 'success', message: 'Draw due to threefold repetition' }),
    onInsufficientMaterial: () => setStatus({ severity: 'warning', message: 'Draw due to insufficient material' }),
  });

  useEffect(()=>{
    console.log({move,history,turn})
  },[move,history,turn])
```
2.  I also want to transmit the moves over socket.io and would want some help figuring out which `fn` to expose .
3. I am using the Chessboard in a tab. Whenever I change tabs I get `r.current.destroy is not a function` from `useChess`

PS: Don't want to create more issues.

**Comment by maxwellhaydn** [comment]
1. For you to really get that integration working, I think I would need to expose chessboard.js's `onDrop` callback in react-simple-chessboard and also update react-chess.js to accept move objects instead of just algebraic notation. The changes to react-chess.js make sense so I can do them regardless, but I'd rather use chessboardjsx instead of changing react-simple-chessboard since chessboardjsx already supports `onDrop`; I just haven't had time to look at chessboardjsx deeper yet.
2. I think for this use case you would also want to run some code in the `onDrop` callback.
3. Can you please open a bug report for the `destroy` error? Thanks!

**Comment by cngeru** [comment]
Emailed @willb335 (Will) the maintainer of `chessboardjsx` and he says he'll be taking sometime before updating the lib (personal reasons). I like `react-simple-chessboard` because of the smoothness and it doesn't break the UI and design  even when on smaller devices unlike chessboardjsx with the issues. 

Hoping you expose the `onDrop` and accept to move objects coz it'll make this lib complete.

Check out this project [https://github.com/Phongtlam/reactchess]( https://github.com/Phongtlam/reactchess) to see how they did it. The project also uses `chessboard.js`

 I can help [link](https://dcngeru.web.app).

**Comment by maxwellhaydn** [comment]
Hi Dennis, I looked at this a little more but it wasn’t as simple as I thought it would be. chessboard.js’s `onDrop` callback requires you to return the string "snapback" if a move should be rejected, but if you call the `move` method from `useChess`, you don’t know if the move is invalid until the `onIllegalMove` callback fires.

**Comment by cngeru** [comment]
Hello Maxwell,
If I'm getting you right, I can listen for `onIllegalMove` and use the `undo` to revert the move ? Is there an example on it ?.
Hoping to get a fix in the upcoming version esp. on the `onDrop` . Been working on a project and it's the only functionality remaining (for the `socket.io` functionality). Also the crash when destroying the board has not been fixed.
Thank you.

**Comment by maxwellhaydn** [comment]
> Hello Maxwell,
> If I'm getting you right, I can listen for `onIllegalMove` and use the `undo` to revert the move ?

Hmm, I'm not sure if that would work either, because you have to define the `onIllegalMove` callback before `undo` is defined. I don't have a good solution for this right now. My original use case for react-simple-chessboard doesn't involve drag-and-drop, so I haven't really explored it very much and it's much more complicated than I anticipated. I'll keep trying to think of a solution.

> Hoping to get a fix in the upcoming version esp. on the `onDrop` . Been working on a project and it's the only functionality remaining (for the `socket.io` functionality). Also the crash when destroying the board has not been fixed.

I'll try to fix that issue soon.

**Comment by cngeru** [comment]
Any fixes on the `onDrop`  and the destroy function ?
Please check out this repo [https://github.com/Phongtlam/reactchess](https://github.com/Phongtlam/reactchess)

**Comment by cngeru** [comment]
@maxwellhaydn  Any fixes on the `onDrop`  and the destroy function ?
Please check out this repo [https://github.com/Phongtlam/reactchess](https://github.com/Phongtlam/reactchess)

**Comment by maxwellhaydn** [comment]
Hi Dennis,

I’m really sorry, I have been too busy with other things to look at this and probably won’t be able to work on it for a while. If you have time to work on it, pull requests are welcome.

**Comment by cngeru** [comment]
Even on the useChess lib bug ?

**Comment by cngeru** [comment]
I'd really want to see a fix on the bugs though please. Been trying to follow your train of thought while going through the code and I've come up short while trying to understand it. Kinda new to programming. Just the 2 fixes please.
Thank you
